//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_DONHANG
    {
        public tb_DONHANG()
        {
            this.tb_ChiTietDonHang = new HashSet<tb_ChiTietDonHang>();
        }
    
        public int MaDH { get; set; }
        public Nullable<int> MaKH { get; set; }
        public Nullable<System.DateTime> NgayDatHang { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<int> MaNV { get; set; }
    
        public virtual ICollection<tb_ChiTietDonHang> tb_ChiTietDonHang { get; set; }
        public virtual tb_KHACHHANG tb_KHACHHANG { get; set; }
        public virtual tb_NHANVIEN tb_NHANVIEN { get; set; }
    }
}
