//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_KHACHHANG
    {
        public tb_KHACHHANG()
        {
            this.tb_TaiKhoan1 = new HashSet<tb_TaiKhoan>();
        }
    
        public int MaKH { get; set; }
        public string TenKH { get; set; }
        public string DiaChi { get; set; }
        public string STD { get; set; }
        public string Email { get; set; }
    
        public virtual tb_DONHANG tb_DONHANG { get; set; }
        public virtual tb_TaiKhoan tb_TaiKhoan { get; set; }
        public virtual ICollection<tb_TaiKhoan> tb_TaiKhoan1 { get; set; }
    }
}
