//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_KhoSach
    {
        public int MaKho { get; set; }
        public Nullable<int> MaSach { get; set; }
        public Nullable<int> TongSoLuong { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
    
        public virtual tb_SACH tb_SACH { get; set; }
    }
}
