//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_NHANVIEN
    {
        public tb_NHANVIEN()
        {
            this.tb_DONHANG = new HashSet<tb_DONHANG>();
            this.tb_NhatKiNhapSach = new HashSet<tb_NhatKiNhapSach>();
            this.tb_TaiKhoan1 = new HashSet<tb_TaiKhoan>();
        }
    
        public int MaNV { get; set; }
        public string HoTen { get; set; }
        public string DiaChi { get; set; }
        public string SDT { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<tb_DONHANG> tb_DONHANG { get; set; }
        public virtual tb_TaiKhoan tb_TaiKhoan { get; set; }
        public virtual ICollection<tb_NhatKiNhapSach> tb_NhatKiNhapSach { get; set; }
        public virtual ICollection<tb_TaiKhoan> tb_TaiKhoan1 { get; set; }
    }
}
