//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_TaiKhoan
    {
        public tb_TaiKhoan()
        {
            this.tb_KHACHHANG = new HashSet<tb_KHACHHANG>();
            this.tb_NHANVIEN = new HashSet<tb_NHANVIEN>();
        }
    
        public string Email { get; set; }
        public string MatKhau { get; set; }
        public string Quyen { get; set; }
        public Nullable<int> MaNV { get; set; }
        public Nullable<int> MaKH { get; set; }
    
        public virtual ICollection<tb_KHACHHANG> tb_KHACHHANG { get; set; }
        public virtual tb_KHACHHANG tb_KHACHHANG1 { get; set; }
        public virtual ICollection<tb_NHANVIEN> tb_NHANVIEN { get; set; }
        public virtual tb_NHANVIEN tb_NHANVIEN1 { get; set; }
    }
}
